"""
Plan schemas for the Planner agent.

Defines structured data contracts for architecture plans and build steps.
"""

from typing import List
from pydantic import BaseModel, Field


class PlanStep(BaseModel):
    """A single discrete step in the application build plan."""

    step_number: int = Field(..., description="1-indexed sequential step number")
    title: str = Field(..., description="Short title of what this step accomplishes")
    description: str = Field(..., description="Detailed instructions and implementation requirements")
    target_files: List[str] = Field(
        default_factory=list,
        description="Files created or modified in this step (e.g. ['index.html', 'style.css'])",
    )


class Plan(BaseModel):
    """Comprehensive architecture and implementation plan generated by the Planner agent."""

    title: str = Field(..., description="Short, descriptive title of the application")
    summary: str = Field(..., description="High-level summary of architecture, layout, and functionality")
    target_files: List[str] = Field(
        default_factory=list,
        description="Full manifest of all files to be generated",
    )
    steps: List[PlanStep] = Field(
        ...,
        description="Ordered sequence of implementation steps for the Coder agent",
    )
